export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";


export const ALL_HOSPITALS_REQUEST = "ALL_HOSPITALS_REQUEST";
export const ALL_HOSPITALS_SUCCESS = "ALL_HOSPITALS_SUCCESS";
export const ALL_HOSPITALS_FAIL = "ALL_HOSPITALS_FAIL";

export const UPDATE_HOSPITAL_REQUEST = "UPDATE_HOSPITAL_REQUEST";
export const UPDATE_HOSPITAL_SUCCESS = "UPDATE_HOSPITAL_SUCCESS";
export const UPDATE_HOSPITAL_RESET = "UPDATE_HOSPITAL_RESET";
export const UPDATE_HOSPITAL_FAIL = "UPDATE_HOSPITAL_FAIL";

export const DELETE_HOSPITAL_REQUEST = "DELETE_HOSPITAL_REQUEST";
export const DELETE_HOSPITAL_SUCCESS = "DELETE_HOSPITAL_SUCCESS";
export const DELETE_HOSPITAL_RESET = "DELETE_HOSPITAL_RESET";
export const DELETE_HOSPITAL_FAIL = "DELETE_HOSPITAL_FAIL";

export const HOSPITAL_DETAILS_REQUEST = "HOSPITAL_DETAILS_REQUEST";
export const HOSPITAL_DETAILS_SUCCESS = "HOSPITAL_DETAILS_SUCCESS";
export const HOSPITAL_DETAILS_FAIL = "HOSPITAL_DETAILS_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS"